spring.application.name=quizz

# Banco H2
spring.datasource.url=jdbc:h2:mem:quizzdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Console H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Thymeleaf
spring.thymeleaf.cache=false

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Página de erro personalizada
spring.web.error.whitelabel.enabled=false
spring.web.error.path=/erro